# Generated by Django 2.0.7 on 2018-07-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_torneo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='city_reference_a',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='city_reference_b',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='referee',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
