# Generated by Django 2.0.7 on 2018-07-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20180724_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='alineaciones',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='heatmap',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='image_streaming',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='stage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
