# Generated by Django 2.0.7 on 2018-07-26 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20180724_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
